# Generated by Django 5.1.3 on 2025-12-04 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('event_registration', 'Event Registration'), ('payment_success', 'Payment Success'), ('course_update', 'Course Update'), ('event_update', 'Event Update'), ('event_reminder', 'Event Reminder'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('comment_reply', 'Comment Reply'), ('admin_announcement', 'Admin Announcement'), ('certificate_ready', 'Certificate Ready')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_type', models.CharField(blank=True, help_text='Type of linked object (course, event, post, etc.)', max_length=50, null=True)),
                ('link_id', models.IntegerField(blank=True, help_text='ID of the linked object', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
