# Generated by Django 5.1.3 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Direct PDF URL', null=True),
        ),
    ]
